//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVGL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVGL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,10,10,500,,,,L,0,,Order:,,
        ///2,10,10,504,,,,M,1,,ABN,MCM,SM
        ///1,0,0,502,,,,H,2,,,,
        ///1,1,0,501,,,,NoEffect,10,,,,
        ///1,2,0,501,,,,,,,,,
        ///1,10,1,501,,,,,,,,,
        ///1,10,2,503,,,,,,,,,.
        /// </summary>
        public static string NewEdgeRules {
            get {
                return ResourceManager.GetString("NewEdgeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500,500,500,200,500,500,500,,,,,,,,,,,
        ///500,500,502,201,500,500,502,,,,,,,,,,,
        ///500,500,501,201,500,500,501,,,,,,,,,,,
        ///500,500,503,200,500,500,1000,,,,,,,,,,,500,500,1000
        ///500,500,504,200,500,500,1000,,,,,,,,,,,
        ///500,502,502,202,500,502,502,,,,,,,,,,,1000,502,502
        ///500,502,501,201,500,502,501,,,,,,,,,,,
        ///500,502,503,201,500,502,1000,,,,,,,,,,,500,502,1000
        ///500,502,504,201,500,502,1000,,,,,,,,,,,
        ///500,501,501,201,500,501,501,,,,,,,,,,,1000,501,501
        ///500,501,503,201,500,501,1000,,,,,,,,,,,500,501,1000
        ///500,501 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewFaRules {
            get {
                return ResourceManager.GetString("NewFaRules", resourceCulture);
            }
        }
    }
}
